name: Deploy to Netlify
on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@master  

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: '22' 

      - name: Install Dependencies
        run: npm install  

      - name: Build Project
        run: npm run build  

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          netlify_auth_token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify_site_id: ${{ secrets.NETLIFY_SITE_ID }}
